/*

initial state
 * first signer
 * empty test file
 * empty code file
 * pending commits

there are the following operations
 * add signer
 * add test with bounty ... should the funds be added too?
 * funds can be added using on chain messages (block generated by Truebit)
 * add encrypted commit
 * apply commit, run tests, perhaps get bounty
 * accept commit
 * should every signer have own test/bounty file?

should we have token transactions here?
 * how to exit?
 * cannot exit if has signed a later block
 * signers can only exit by messaging blocks?
 * let's have just signers making token transactions

if a signer is not awake, can be removed using onchain message

wasm c++ tools
 * wast -> wasm
 * interpreter
 * perhaps binaryen? but does it have an interpreter?

can audit and lock the repo

perhaps all participants are signers?

protocol for signing
 * a signer will propose a block
 * other signers will then accept it
 * a block can be rejected
 * if somebody rejected the block, then the next proposition can be signed
 * if somebody both accepted and rejected a block, then can be punished

resolving this
 * if there are two valid headers with same serial, a signer will get slashed
 * this will be a signer who has rejected one of these headers

*/


