
/*

initial state
 * first signer
 * empty test file
 * empty code file
 * pending commits

there are the following operations
 * add signer
 * add test with bounty ... should the funds be added too?
 * funds can be added using on chain messages (block generated by Truebit)
 * add encrypted commit
 * apply commit, run tests

should we have token transactions here?
 * how to exit?
 * cannot exit if has signed a later block
 * signers can only exit by messaging blocks?

*/


